# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d164bf67cc04e1e9bb209fb42540ec169a09e1249bf21e8e60bf9891219c23312b11a5f845b412439ab0a47a6c98d3f503fcb239935ac82b91eed84b9b59aa7

test:
  secret_key_base: 60925b7d0356f00dcf54698374852eb27966cf844c9d2532557277b0a4e3c669f099d2cbe68c91d4e8200aa01930ced9a083a9d3aa43307d225949d109304990

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
